#!/usr/bin/env bash
#
# Generate the Homebrew formula for codeanalyzer-python (the `canpy` CLI).
#
# Unlike the codeanalyzer-typescript sibling -- which ships a single self-contained
# binary that the formula just downloads -- codeanalyzer-python is a pure-Python
# package published to PyPI with heavy native dependencies (ray, pandas, numpy).
# Vendoring every transitive dependency as a Homebrew `resource` is impractical
# (ray is not buildable from an sdist), and pip-installing at build time is blocked
# by Homebrew's network sandbox.
#
# So the formula stays tiny: it depends on `uv` and installs version-pinned wrapper
# scripts that run the published PyPI release via `uvx` (uv resolves and caches the
# isolated environment on first run). This keeps `brew install` sandbox-safe (no
# network at build time) while pinning the exact released version.
#
# Homebrew requires every formula to declare a source `url` + `sha256` for its
# stable spec, so we point at the released sdist (byte-identical to the PyPI one).
# The install method ignores the unpacked source and just writes uv wrappers, but
# the url anchors the version and satisfies Homebrew's spec requirement.
#
# Usage:
#   REPO=codellm-devkit/codeanalyzer-python VERSION=0.2.0 SHA256=<sdist sha256> \
#     ./generate_formula.sh > codeanalyzer-python.rb
#
set -euo pipefail

REPO="${REPO:?set REPO, e.g. codellm-devkit/codeanalyzer-python}"
VERSION="${VERSION:?set VERSION, e.g. 0.2.0}"
SHA256="${SHA256:?set SHA256 of the released sdist}"
SDIST_URL="https://github.com/${REPO}/releases/download/v${VERSION}/codeanalyzer_python-${VERSION}.tar.gz"

cat <<EOF
# This file is auto-generated by packaging/homebrew/generate_formula.sh on release.
# Do not edit by hand -- changes will be overwritten on the next tag.
class CodeanalyzerPython < Formula
  desc "CLDK Python analyzer (canpy) -- emits canonical analysis.json or a Neo4j graph"
  homepage "https://github.com/${REPO}"
  url "${SDIST_URL}"
  sha256 "${SHA256}"
  version "${VERSION}"
  license "Apache-2.0"

  # codeanalyzer-python is a pure-Python PyPI package with heavy native deps
  # (ray, pandas, numpy). Rather than vendor every transitive dependency as a
  # Homebrew resource, install the pinned PyPI release as an isolated uv tool;
  # uv resolves and caches the environment on first run.
  depends_on "uv"

  def install
    %w[canpy codeanalyzer].each do |exe|
      (bin/exe).write <<~SH
        #!/bin/bash
        exec uvx --from "codeanalyzer-python==#{version}" #{exe} "\$@"
      SH
      chmod 0755, bin/exe
    end
  end

  test do
    assert_match "codeanalyzer-python==#{version}", File.read(bin/"canpy")
    assert_predicate bin/"canpy", :executable?
  end
end
EOF
